//! AutomationRule DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::AutomationRule;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::FoundationTriggerKind;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new AutomationRule
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateAutomationRuleDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub model: String,
    #[serde(alias = "trigger_kind")]
    pub trigger_kind: FoundationTriggerKind,
    #[cfg_attr(feature = "validation", validate(length(max = 160)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "trigger_pattern")]
    pub trigger_pattern: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 63)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "time_field")]
    pub time_field: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "delay_minutes")]
    pub delay_minutes: Option<i32>,
    pub actions: serde_json::Value,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "created_by_source")]
    pub created_by_source: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a AutomationRule
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateAutomationRuleDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub model: String,
    #[serde(alias = "trigger_kind")]
    pub trigger_kind: FoundationTriggerKind,
    #[cfg_attr(feature = "validation", validate(length(max = 160)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "trigger_pattern")]
    pub trigger_pattern: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 63)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "time_field")]
    pub time_field: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "delay_minutes")]
    pub delay_minutes: Option<i32>,
    pub actions: serde_json::Value,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "created_by_source")]
    pub created_by_source: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a AutomationRule
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchAutomationRuleDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "trigger_kind")]
    pub trigger_kind: Option<FoundationTriggerKind>,
    #[cfg_attr(feature = "validation", validate(length(max = 160)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "trigger_pattern")]
    pub trigger_pattern: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 63)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "time_field")]
    pub time_field: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "delay_minutes")]
    pub delay_minutes: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actions: Option<serde_json::Value>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "created_by_source")]
    pub created_by_source: Option<String>,
}

impl PatchAutomationRuleDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.name.is_some() || self.description.is_some() || self.model.is_some() || self.trigger_kind.is_some() || self.trigger_pattern.is_some() || self.time_field.is_some() || self.delay_minutes.is_some() || self.actions.is_some() || self.active.is_some() || self.created_by_source.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for AutomationRule entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AutomationRuleResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub description: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub model: String,
    pub trigger_kind: FoundationTriggerKind,
    pub trigger_pattern: Option<String>,
    pub time_field: Option<String>,
    pub delay_minutes: Option<i32>,
    pub actions: serde_json::Value,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
    pub created_by_source: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for AutomationRule entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AutomationRuleListResponseDto {
    /// List of items
    pub items: Vec<AutomationRuleResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl AutomationRuleListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<AutomationRuleResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AutomationRuleSummaryDto {
    pub id: Uuid,
    pub name: String,
    pub description: Option<String>,
    pub model: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<AutomationRule> for AutomationRuleResponseDto {
    fn from(entity: AutomationRule) -> Self {
        Self {
            id: entity.id,
            name: entity.name,
            description: entity.description,
            model: entity.model,
            trigger_kind: entity.trigger_kind,
            trigger_pattern: entity.trigger_pattern,
            time_field: entity.time_field,
            delay_minutes: entity.delay_minutes,
            actions: entity.actions,
            active: entity.active,
            created_by_source: entity.created_by_source,
            metadata: entity.metadata,
        }
    }
}

impl From<AutomationRule> for AutomationRuleSummaryDto {
    fn from(entity: AutomationRule) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            name: entity.name,
            description: entity.description,
            model: entity.model,
            created_at,
        }
    }
}

impl From<CreateAutomationRuleDto> for AutomationRule {
    fn from(dto: CreateAutomationRuleDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            name: dto.name,
            description: dto.description,
            model: dto.model,
            trigger_kind: dto.trigger_kind,
            trigger_pattern: dto.trigger_pattern,
            time_field: dto.time_field,
            delay_minutes: dto.delay_minutes,
            actions: dto.actions,
            active: dto.active,
            created_by_source: dto.created_by_source,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&AutomationRule> for AutomationRuleResponseDto {
    fn from(entity: &AutomationRule) -> Self {
        Self {
            id: entity.id.clone(),
            name: entity.name.clone(),
            description: entity.description.clone(),
            model: entity.model.clone(),
            trigger_kind: entity.trigger_kind.clone(),
            trigger_pattern: entity.trigger_pattern.clone(),
            time_field: entity.time_field.clone(),
            delay_minutes: entity.delay_minutes.clone(),
            actions: entity.actions.clone(),
            active: entity.active.clone(),
            created_by_source: entity.created_by_source.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateAutomationRuleDto> for AutomationRule {
    fn from_create_dto(dto: CreateAutomationRuleDto) -> backbone_core::ServiceResult<Self> {
        Ok(AutomationRule::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateAutomationRuleDto> for AutomationRule {
    fn apply_update(mut self, dto: UpdateAutomationRuleDto) -> backbone_core::ServiceResult<Self> {
        self.name = dto.name;
        self.description = dto.description;
        self.model = dto.model;
        self.trigger_kind = dto.trigger_kind;
        self.trigger_pattern = dto.trigger_pattern;
        self.time_field = dto.time_field;
        self.delay_minutes = dto.delay_minutes;
        self.actions = dto.actions;
        self.active = dto.active;
        self.created_by_source = dto.created_by_source;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to AutomationRule here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
