//! AutomationRun DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::AutomationRun;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::FoundationRunStatus;
use crate::domain::entity::FoundationTriggerKind;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new AutomationRun
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateAutomationRunDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "automation_id")]
    pub automation_id: Uuid,
    pub trigger: FoundationTriggerKind,
    pub status: FoundationRunStatus,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "envelope_id")]
    pub envelope_id: String,
    #[cfg_attr(feature = "validation", validate(length(max = 160)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "source_event_type")]
    pub source_event_type: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 160)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "aggregate_id")]
    pub aggregate_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "parent_run_id")]
    pub parent_run_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub depth: i32,
    #[serde(alias = "actions_applied")]
    pub actions_applied: serde_json::Value,
    #[serde(alias = "effect_event_ids")]
    pub effect_event_ids: serde_json::Value,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "occurred_at")]
    pub occurred_at: DateTime<Utc>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a AutomationRun
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateAutomationRunDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "automation_id")]
    pub automation_id: Uuid,
    pub trigger: FoundationTriggerKind,
    pub status: FoundationRunStatus,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "envelope_id")]
    pub envelope_id: String,
    #[cfg_attr(feature = "validation", validate(length(max = 160)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "source_event_type")]
    pub source_event_type: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 160)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "aggregate_id")]
    pub aggregate_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "parent_run_id")]
    pub parent_run_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub depth: i32,
    #[serde(alias = "actions_applied")]
    pub actions_applied: serde_json::Value,
    #[serde(alias = "effect_event_ids")]
    pub effect_event_ids: serde_json::Value,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "occurred_at")]
    pub occurred_at: DateTime<Utc>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a AutomationRun
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchAutomationRunDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "automation_id")]
    pub automation_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub trigger: Option<FoundationTriggerKind>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<FoundationRunStatus>,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "envelope_id")]
    pub envelope_id: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 160)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "source_event_type")]
    pub source_event_type: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 160)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "aggregate_id")]
    pub aggregate_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "parent_run_id")]
    pub parent_run_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub depth: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "actions_applied")]
    pub actions_applied: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "effect_event_ids")]
    pub effect_event_ids: Option<serde_json::Value>,
    #[cfg_attr(feature = "validation", validate(length(max = 500)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "occurred_at")]
    pub occurred_at: Option<DateTime<Utc>>,
}

impl PatchAutomationRunDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.automation_id.is_some() || self.trigger.is_some() || self.status.is_some() || self.envelope_id.is_some() || self.source_event_type.is_some() || self.aggregate_id.is_some() || self.parent_run_id.is_some() || self.depth.is_some() || self.actions_applied.is_some() || self.effect_event_ids.is_some() || self.detail.is_some() || self.occurred_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for AutomationRun entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AutomationRunResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub automation_id: Uuid,
    pub trigger: FoundationTriggerKind,
    pub status: FoundationRunStatus,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub envelope_id: String,
    pub source_event_type: Option<String>,
    pub aggregate_id: Option<String>,
    pub parent_run_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub depth: i32,
    pub actions_applied: serde_json::Value,
    pub effect_event_ids: serde_json::Value,
    pub detail: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub occurred_at: DateTime<Utc>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for AutomationRun entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AutomationRunListResponseDto {
    /// List of items
    pub items: Vec<AutomationRunResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl AutomationRunListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<AutomationRunResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AutomationRunSummaryDto {
    pub id: Uuid,
    pub automation_id: Uuid,
    pub trigger: FoundationTriggerKind,
    pub status: FoundationRunStatus,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<AutomationRun> for AutomationRunResponseDto {
    fn from(entity: AutomationRun) -> Self {
        Self {
            id: entity.id,
            automation_id: entity.automation_id,
            trigger: entity.trigger,
            status: entity.status,
            envelope_id: entity.envelope_id,
            source_event_type: entity.source_event_type,
            aggregate_id: entity.aggregate_id,
            parent_run_id: entity.parent_run_id,
            depth: entity.depth,
            actions_applied: entity.actions_applied,
            effect_event_ids: entity.effect_event_ids,
            detail: entity.detail,
            occurred_at: entity.occurred_at,
            metadata: entity.metadata,
        }
    }
}

impl From<AutomationRun> for AutomationRunSummaryDto {
    fn from(entity: AutomationRun) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            automation_id: entity.automation_id,
            trigger: entity.trigger,
            status: entity.status,
            created_at,
        }
    }
}

impl From<CreateAutomationRunDto> for AutomationRun {
    fn from(dto: CreateAutomationRunDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            automation_id: dto.automation_id,
            trigger: dto.trigger,
            status: dto.status,
            envelope_id: dto.envelope_id,
            source_event_type: dto.source_event_type,
            aggregate_id: dto.aggregate_id,
            parent_run_id: dto.parent_run_id,
            depth: dto.depth,
            actions_applied: dto.actions_applied,
            effect_event_ids: dto.effect_event_ids,
            detail: dto.detail,
            occurred_at: dto.occurred_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&AutomationRun> for AutomationRunResponseDto {
    fn from(entity: &AutomationRun) -> Self {
        Self {
            id: entity.id.clone(),
            automation_id: entity.automation_id.clone(),
            trigger: entity.trigger.clone(),
            status: entity.status.clone(),
            envelope_id: entity.envelope_id.clone(),
            source_event_type: entity.source_event_type.clone(),
            aggregate_id: entity.aggregate_id.clone(),
            parent_run_id: entity.parent_run_id.clone(),
            depth: entity.depth.clone(),
            actions_applied: entity.actions_applied.clone(),
            effect_event_ids: entity.effect_event_ids.clone(),
            detail: entity.detail.clone(),
            occurred_at: entity.occurred_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateAutomationRunDto> for AutomationRun {
    fn from_create_dto(dto: CreateAutomationRunDto) -> backbone_core::ServiceResult<Self> {
        Ok(AutomationRun::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateAutomationRunDto> for AutomationRun {
    fn apply_update(mut self, dto: UpdateAutomationRunDto) -> backbone_core::ServiceResult<Self> {
        self.automation_id = dto.automation_id;
        self.trigger = dto.trigger;
        self.status = dto.status;
        self.envelope_id = dto.envelope_id;
        self.source_event_type = dto.source_event_type;
        self.aggregate_id = dto.aggregate_id;
        self.parent_run_id = dto.parent_run_id;
        self.depth = dto.depth;
        self.actions_applied = dto.actions_applied;
        self.effect_event_ids = dto.effect_event_ids;
        self.detail = dto.detail;
        self.occurred_at = dto.occurred_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to AutomationRun here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
