//! SchedulerPosture DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::SchedulerPosture;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::FoundationSchedulerPosture;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new SchedulerPosture
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateSchedulerPostureDto {
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub singleton: bool,
    pub posture: FoundationSchedulerPosture,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "time_rule_count")]
    pub time_rule_count: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "min_delay_minutes")]
    pub min_delay_minutes: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "interval_minutes")]
    pub interval_minutes: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_evaluated_at")]
    pub last_evaluated_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "last_fired_count")]
    pub last_fired_count: i32,
    #[cfg_attr(feature = "validation", validate(length(max = 300)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_deviation_note")]
    pub last_deviation_note: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a SchedulerPosture
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateSchedulerPostureDto {
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub singleton: bool,
    pub posture: FoundationSchedulerPosture,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "time_rule_count")]
    pub time_rule_count: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "min_delay_minutes")]
    pub min_delay_minutes: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "interval_minutes")]
    pub interval_minutes: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_evaluated_at")]
    pub last_evaluated_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "last_fired_count")]
    pub last_fired_count: i32,
    #[cfg_attr(feature = "validation", validate(length(max = 300)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_deviation_note")]
    pub last_deviation_note: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a SchedulerPosture
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchSchedulerPostureDto {
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub singleton: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub posture: Option<FoundationSchedulerPosture>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "time_rule_count")]
    pub time_rule_count: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "min_delay_minutes")]
    pub min_delay_minutes: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "interval_minutes")]
    pub interval_minutes: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "last_evaluated_at")]
    pub last_evaluated_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "last_fired_count")]
    pub last_fired_count: Option<i32>,
    #[cfg_attr(feature = "validation", validate(length(max = 300)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "last_deviation_note")]
    pub last_deviation_note: Option<String>,
}

impl PatchSchedulerPostureDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.singleton.is_some() || self.posture.is_some() || self.time_rule_count.is_some() || self.min_delay_minutes.is_some() || self.interval_minutes.is_some() || self.last_evaluated_at.is_some() || self.last_fired_count.is_some() || self.last_deviation_note.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for SchedulerPosture entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SchedulerPostureResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub singleton: bool,
    pub posture: FoundationSchedulerPosture,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub time_rule_count: i32,
    pub min_delay_minutes: Option<i32>,
    pub interval_minutes: Option<i32>,
    pub last_evaluated_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub last_fired_count: i32,
    pub last_deviation_note: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for SchedulerPosture entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SchedulerPostureListResponseDto {
    /// List of items
    pub items: Vec<SchedulerPostureResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl SchedulerPostureListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<SchedulerPostureResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SchedulerPostureSummaryDto {
    pub id: Uuid,
    pub singleton: bool,
    pub posture: FoundationSchedulerPosture,
    pub time_rule_count: i32,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<SchedulerPosture> for SchedulerPostureResponseDto {
    fn from(entity: SchedulerPosture) -> Self {
        Self {
            id: entity.id,
            singleton: entity.singleton,
            posture: entity.posture,
            time_rule_count: entity.time_rule_count,
            min_delay_minutes: entity.min_delay_minutes,
            interval_minutes: entity.interval_minutes,
            last_evaluated_at: entity.last_evaluated_at,
            last_fired_count: entity.last_fired_count,
            last_deviation_note: entity.last_deviation_note,
            metadata: entity.metadata,
        }
    }
}

impl From<SchedulerPosture> for SchedulerPostureSummaryDto {
    fn from(entity: SchedulerPosture) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            singleton: entity.singleton,
            posture: entity.posture,
            time_rule_count: entity.time_rule_count,
            created_at,
        }
    }
}

impl From<CreateSchedulerPostureDto> for SchedulerPosture {
    fn from(dto: CreateSchedulerPostureDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            singleton: dto.singleton,
            posture: dto.posture,
            time_rule_count: dto.time_rule_count,
            min_delay_minutes: dto.min_delay_minutes,
            interval_minutes: dto.interval_minutes,
            last_evaluated_at: dto.last_evaluated_at,
            last_fired_count: dto.last_fired_count,
            last_deviation_note: dto.last_deviation_note,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&SchedulerPosture> for SchedulerPostureResponseDto {
    fn from(entity: &SchedulerPosture) -> Self {
        Self {
            id: entity.id.clone(),
            singleton: entity.singleton.clone(),
            posture: entity.posture.clone(),
            time_rule_count: entity.time_rule_count.clone(),
            min_delay_minutes: entity.min_delay_minutes.clone(),
            interval_minutes: entity.interval_minutes.clone(),
            last_evaluated_at: entity.last_evaluated_at.clone(),
            last_fired_count: entity.last_fired_count.clone(),
            last_deviation_note: entity.last_deviation_note.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateSchedulerPostureDto> for SchedulerPosture {
    fn from_create_dto(dto: CreateSchedulerPostureDto) -> backbone_core::ServiceResult<Self> {
        Ok(SchedulerPosture::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateSchedulerPostureDto> for SchedulerPosture {
    fn apply_update(mut self, dto: UpdateSchedulerPostureDto) -> backbone_core::ServiceResult<Self> {
        self.singleton = dto.singleton;
        self.posture = dto.posture;
        self.time_rule_count = dto.time_rule_count;
        self.min_delay_minutes = dto.min_delay_minutes;
        self.interval_minutes = dto.interval_minutes;
        self.last_evaluated_at = dto.last_evaluated_at;
        self.last_fired_count = dto.last_fired_count;
        self.last_deviation_note = dto.last_deviation_note;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to SchedulerPosture here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
