//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod automation_rule_specification;
pub mod automation_run_specification;
pub mod scheduler_posture_specification;

// <<< CUSTOM
// END CUSTOM
