//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod automation_rule_domain_policy;
pub mod automation_run_domain_policy;
pub mod scheduler_posture_domain_policy;

pub use automation_rule_domain_policy::AutomationRuleDomainPolicy;
pub use automation_run_domain_policy::AutomationRunDomainPolicy;
pub use scheduler_posture_domain_policy::SchedulerPostureDomainPolicy;

// <<< CUSTOM
// END CUSTOM
