//! Application service for AutomationRun entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `automation_run_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateAutomationRunDto, UpdateAutomationRunDto};
use crate::domain::entity::AutomationRun;
use crate::infrastructure::persistence::AutomationRunRepository;

/// Application service for AutomationRun entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `automation_run_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct AutomationRunServiceCustom {
///     inner: Arc<AutomationRunService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type AutomationRunService = GenericCrudService<
    AutomationRun,
    CreateAutomationRunDto,
    UpdateAutomationRunDto,
    AutomationRunRepository,
>;

// <<< CUSTOM
// END CUSTOM
