//! Application service for AutomationRule entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `automation_rule_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateAutomationRuleDto, UpdateAutomationRuleDto};
use crate::domain::entity::AutomationRule;
use crate::infrastructure::persistence::AutomationRuleRepository;

/// Application service for AutomationRule entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `automation_rule_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct AutomationRuleServiceCustom {
///     inner: Arc<AutomationRuleService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type AutomationRuleService = GenericCrudService<
    AutomationRule,
    CreateAutomationRuleDto,
    UpdateAutomationRuleDto,
    AutomationRuleRepository,
>;

// <<< CUSTOM
// END CUSTOM
