//! Application service for SchedulerPosture entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `scheduler_posture_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateSchedulerPostureDto, UpdateSchedulerPostureDto};
use crate::domain::entity::SchedulerPosture;
use crate::infrastructure::persistence::SchedulerPostureRepository;

/// Application service for SchedulerPosture entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `scheduler_posture_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct SchedulerPostureServiceCustom {
///     inner: Arc<SchedulerPostureService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type SchedulerPostureService = GenericCrudService<
    SchedulerPosture,
    CreateSchedulerPostureDto,
    UpdateSchedulerPostureDto,
    SchedulerPostureRepository,
>;

// <<< CUSTOM
// END CUSTOM
