-- AutomationRule Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the foundation_ext.foundation_automation_rules table.
-- Customize this file to add your initial data.

-- INSERT INTO foundation_ext.foundation_automation_rules (
--     id,
--     name,
--     description,
--     model,
--     trigger_kind,
--     trigger_pattern,
--     time_field,
--     delay_minutes,
--     actions,
--     active,
--     created_by_source,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO foundation_ext.foundation_automation_rules (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

