-- AutomationRun Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the foundation_ext.foundation_automation_runs table.
-- Customize this file to add your initial data.

-- INSERT INTO foundation_ext.foundation_automation_runs (
--     id,
--     automation_id,
--     trigger,
--     status,
--     envelope_id,
--     source_event_type,
--     aggregate_id,
--     parent_run_id,
--     depth,
--     actions_applied,
--     effect_event_ids,
--     detail,
--     occurred_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO foundation_ext.foundation_automation_runs (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

