-- SchedulerPosture Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the foundation_ext.foundation_scheduler_posture table.
-- Customize this file to add your initial data.

-- INSERT INTO foundation_ext.foundation_scheduler_posture (
--     id,
--     singleton,
--     posture,
--     time_rule_count,
--     min_delay_minutes,
--     interval_minutes,
--     last_evaluated_at,
--     last_fired_count,
--     last_deviation_note,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO foundation_ext.foundation_scheduler_posture (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

