-- Migration: Create foundation_scheduler_posture table
-- Generated by metaphor-schema

-- Create foundation_scheduler_posture enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'foundation_scheduler_posture') THEN
        CREATE TYPE foundation_scheduler_posture AS ENUM ('inactive', 'active');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS foundation_ext;

CREATE TABLE IF NOT EXISTS foundation_ext.foundation_scheduler_posture (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    singleton BOOLEAN NOT NULL DEFAULT TRUE,
    posture foundation_scheduler_posture NOT NULL DEFAULT 'inactive',
    time_rule_count INTEGER NOT NULL DEFAULT 0,
    min_delay_minutes INTEGER,
    interval_minutes INTEGER,
    last_evaluated_at TIMESTAMPTZ,
    last_fired_count INTEGER NOT NULL DEFAULT 0,
    last_deviation_note TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_foundation_scheduler_posture_singleton ON foundation_ext.foundation_scheduler_posture (singleton);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_foundation_scheduler_posture_metadata_gin ON foundation_ext.foundation_scheduler_posture USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_foundation_scheduler_posture_metadata_deleted_at ON foundation_ext.foundation_scheduler_posture ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_foundation_scheduler_posture_metadata_created_at ON foundation_ext.foundation_scheduler_posture ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_foundation_scheduler_posture_metadata_updated_at ON foundation_ext.foundation_scheduler_posture ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION foundation_ext.foundation_scheduler_posture_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS foundation_scheduler_posture_insert_audit ON foundation_ext.foundation_scheduler_posture;
CREATE TRIGGER foundation_scheduler_posture_insert_audit BEFORE INSERT ON foundation_ext.foundation_scheduler_posture
    FOR EACH ROW EXECUTE FUNCTION foundation_ext.foundation_scheduler_posture_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS foundation_scheduler_posture_update_audit ON foundation_ext.foundation_scheduler_posture;
CREATE TRIGGER foundation_scheduler_posture_update_audit BEFORE UPDATE ON foundation_ext.foundation_scheduler_posture
    FOR EACH ROW EXECUTE FUNCTION foundation_ext.foundation_scheduler_posture_audit_timestamp();
