-- Audit Triggers Migration for foundation_ext module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: AutomationRule (foundation_ext.foundation_automation_rules)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION foundation_ext.foundation_automation_rules_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS foundation_automation_rules_insert_audit ON foundation_ext.foundation_automation_rules;
CREATE TRIGGER foundation_automation_rules_insert_audit BEFORE INSERT ON foundation_ext.foundation_automation_rules
    FOR EACH ROW EXECUTE FUNCTION foundation_ext.foundation_automation_rules_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS foundation_automation_rules_update_audit ON foundation_ext.foundation_automation_rules;
CREATE TRIGGER foundation_automation_rules_update_audit BEFORE UPDATE ON foundation_ext.foundation_automation_rules
    FOR EACH ROW EXECUTE FUNCTION foundation_ext.foundation_automation_rules_audit_timestamp();

-- ==============================================================================
-- Table: AutomationRun (foundation_ext.foundation_automation_runs)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION foundation_ext.foundation_automation_runs_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS foundation_automation_runs_insert_audit ON foundation_ext.foundation_automation_runs;
CREATE TRIGGER foundation_automation_runs_insert_audit BEFORE INSERT ON foundation_ext.foundation_automation_runs
    FOR EACH ROW EXECUTE FUNCTION foundation_ext.foundation_automation_runs_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS foundation_automation_runs_update_audit ON foundation_ext.foundation_automation_runs;
CREATE TRIGGER foundation_automation_runs_update_audit BEFORE UPDATE ON foundation_ext.foundation_automation_runs
    FOR EACH ROW EXECUTE FUNCTION foundation_ext.foundation_automation_runs_audit_timestamp();

-- ==============================================================================
-- Table: SchedulerPosture (foundation_ext.foundation_scheduler_posture)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION foundation_ext.foundation_scheduler_posture_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS foundation_scheduler_posture_insert_audit ON foundation_ext.foundation_scheduler_posture;
CREATE TRIGGER foundation_scheduler_posture_insert_audit BEFORE INSERT ON foundation_ext.foundation_scheduler_posture
    FOR EACH ROW EXECUTE FUNCTION foundation_ext.foundation_scheduler_posture_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS foundation_scheduler_posture_update_audit ON foundation_ext.foundation_scheduler_posture;
CREATE TRIGGER foundation_scheduler_posture_update_audit BEFORE UPDATE ON foundation_ext.foundation_scheduler_posture
    FOR EACH ROW EXECUTE FUNCTION foundation_ext.foundation_scheduler_posture_audit_timestamp();

