-- Migration: Create foundation_automation_runs table
-- Generated by metaphor-schema

-- Create foundation_trigger_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'foundation_trigger_kind') THEN
        CREATE TYPE foundation_trigger_kind AS ENUM ('on_event', 'on_deleted', 'on_time');
    END IF;
END
$$;

-- Create foundation_run_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'foundation_run_status') THEN
        CREATE TYPE foundation_run_status AS ENUM ('fired', 'suppressed_self_trigger', 'depth_capped', 'skipped_model_mismatch', 'refused_body');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS foundation_ext;

CREATE TABLE IF NOT EXISTS foundation_ext.foundation_automation_runs (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    automation_id UUID NOT NULL,
    trigger foundation_trigger_kind NOT NULL,
    status foundation_run_status NOT NULL DEFAULT 'fired',
    envelope_id TEXT NOT NULL,
    source_event_type TEXT,
    aggregate_id TEXT,
    parent_run_id UUID,
    depth INTEGER NOT NULL DEFAULT 0,
    actions_applied JSONB NOT NULL,
    effect_event_ids JSONB NOT NULL,
    detail TEXT,
    occurred_at TIMESTAMPTZ NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_foundation_automation_runs_automation_id_occurred_at ON foundation_ext.foundation_automation_runs (automation_id, occurred_at);

CREATE INDEX IF NOT EXISTS idx_foundation_automation_runs_status ON foundation_ext.foundation_automation_runs (status);

CREATE INDEX IF NOT EXISTS idx_foundation_automation_runs_envelope_id ON foundation_ext.foundation_automation_runs (envelope_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_foundation_automation_runs_metadata_gin ON foundation_ext.foundation_automation_runs USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_foundation_automation_runs_metadata_deleted_at ON foundation_ext.foundation_automation_runs ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_foundation_automation_runs_metadata_created_at ON foundation_ext.foundation_automation_runs ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_foundation_automation_runs_metadata_updated_at ON foundation_ext.foundation_automation_runs ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION foundation_ext.foundation_automation_runs_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS foundation_automation_runs_insert_audit ON foundation_ext.foundation_automation_runs;
CREATE TRIGGER foundation_automation_runs_insert_audit BEFORE INSERT ON foundation_ext.foundation_automation_runs
    FOR EACH ROW EXECUTE FUNCTION foundation_ext.foundation_automation_runs_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS foundation_automation_runs_update_audit ON foundation_ext.foundation_automation_runs;
CREATE TRIGGER foundation_automation_runs_update_audit BEFORE UPDATE ON foundation_ext.foundation_automation_runs
    FOR EACH ROW EXECUTE FUNCTION foundation_ext.foundation_automation_runs_audit_timestamp();
