-- Enum types for foundation_ext module
-- Generated by metaphor-schema

-- Create foundation_trigger_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'foundation_trigger_kind') THEN
        CREATE TYPE foundation_trigger_kind AS ENUM ('on_event', 'on_deleted', 'on_time');
    END IF;
END
$$;

-- Create foundation_run_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'foundation_run_status') THEN
        CREATE TYPE foundation_run_status AS ENUM ('fired', 'suppressed_self_trigger', 'depth_capped', 'skipped_model_mismatch', 'refused_body');
    END IF;
END
$$;

-- Create foundation_scheduler_posture enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'foundation_scheduler_posture') THEN
        CREATE TYPE foundation_scheduler_posture AS ENUM ('inactive', 'active');
    END IF;
END
$$;

