-- Migration: Create foundation_automation_rules table
-- Generated by metaphor-schema

-- Create foundation_trigger_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'foundation_trigger_kind') THEN
        CREATE TYPE foundation_trigger_kind AS ENUM ('on_event', 'on_deleted', 'on_time');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS foundation_ext;

CREATE TABLE IF NOT EXISTS foundation_ext.foundation_automation_rules (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    description TEXT,
    model TEXT NOT NULL,
    trigger_kind foundation_trigger_kind NOT NULL DEFAULT 'on_event',
    trigger_pattern TEXT,
    time_field TEXT,
    delay_minutes INTEGER,
    actions JSONB NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by_source TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_foundation_automation_rules_active_trigger_kind ON foundation_ext.foundation_automation_rules (active, trigger_kind);

CREATE INDEX IF NOT EXISTS idx_foundation_automation_rules_trigger_pattern ON foundation_ext.foundation_automation_rules (trigger_pattern);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_foundation_automation_rules_metadata_gin ON foundation_ext.foundation_automation_rules USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_foundation_automation_rules_metadata_deleted_at ON foundation_ext.foundation_automation_rules ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_foundation_automation_rules_metadata_created_at ON foundation_ext.foundation_automation_rules ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_foundation_automation_rules_metadata_updated_at ON foundation_ext.foundation_automation_rules ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION foundation_ext.foundation_automation_rules_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS foundation_automation_rules_insert_audit ON foundation_ext.foundation_automation_rules;
CREATE TRIGGER foundation_automation_rules_insert_audit BEFORE INSERT ON foundation_ext.foundation_automation_rules
    FOR EACH ROW EXECUTE FUNCTION foundation_ext.foundation_automation_rules_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS foundation_automation_rules_update_audit ON foundation_ext.foundation_automation_rules;
CREATE TRIGGER foundation_automation_rules_update_audit BEFORE UPDATE ON foundation_ext.foundation_automation_rules
    FOR EACH ROW EXECUTE FUNCTION foundation_ext.foundation_automation_rules_audit_timestamp();
