//! Event handler trait for AutomationRun events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::AutomationRunEvent;

/// Event handler for AutomationRun events.
/// Implement this trait to react to AutomationRun lifecycle events.
pub trait AutomationRunEventHandler: EventHandler<AutomationRunEvent> {}
