//! Domain events for AutomationRule entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::AutomationRule;

/// Domain events for AutomationRule — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<AutomationRule>)` variant.
pub type AutomationRuleEvent = CrudEvent<AutomationRule>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for AutomationRule events.
pub type AutomationRuleEventPublisher = Arc<dyn CrudEventPublisher<AutomationRule> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopAutomationRuleEventPublisher = NoOpCrudEventPublisher<AutomationRule>;
