//! Event handler trait for AutomationRule events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::AutomationRuleEvent;

/// Event handler for AutomationRule events.
/// Implement this trait to react to AutomationRule lifecycle events.
pub trait AutomationRuleEventHandler: EventHandler<AutomationRuleEvent> {}
