//! Domain events for AutomationRun entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::AutomationRun;

/// Domain events for AutomationRun — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<AutomationRun>)` variant.
pub type AutomationRunEvent = CrudEvent<AutomationRun>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for AutomationRun events.
pub type AutomationRunEventPublisher = Arc<dyn CrudEventPublisher<AutomationRun> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopAutomationRunEventPublisher = NoOpCrudEventPublisher<AutomationRun>;
