//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod automation_rule_events;
pub mod automation_rule_event_handlers;
pub mod automation_run_events;
pub mod automation_run_event_handlers;
pub mod scheduler_posture_events;
pub mod scheduler_posture_event_handlers;

pub use automation_rule_events::{AutomationRuleEvent, AutomationRuleEventPublisher, NoopAutomationRuleEventPublisher};
pub use automation_rule_event_handlers::AutomationRuleEventHandler;
pub use automation_run_events::{AutomationRunEvent, AutomationRunEventPublisher, NoopAutomationRunEventPublisher};
pub use automation_run_event_handlers::AutomationRunEventHandler;
pub use scheduler_posture_events::{SchedulerPostureEvent, SchedulerPostureEventPublisher, NoopSchedulerPostureEventPublisher};
pub use scheduler_posture_event_handlers::SchedulerPostureEventHandler;

// <<< CUSTOM
// END CUSTOM
