//! Event handler trait for SchedulerPosture events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::SchedulerPostureEvent;

/// Event handler for SchedulerPosture events.
/// Implement this trait to react to SchedulerPosture lifecycle events.
pub trait SchedulerPostureEventHandler: EventHandler<SchedulerPostureEvent> {}
