//! Domain events for SchedulerPosture entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::SchedulerPosture;

/// Domain events for SchedulerPosture — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<SchedulerPosture>)` variant.
pub type SchedulerPostureEvent = CrudEvent<SchedulerPosture>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for SchedulerPosture events.
pub type SchedulerPostureEventPublisher = Arc<dyn CrudEventPublisher<SchedulerPosture> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopSchedulerPostureEventPublisher = NoOpCrudEventPublisher<SchedulerPosture>;
