//! Value Objects
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Value Objects - immutable types defined by their attributes.

mod timestamps;
mod metadata;

// Re-exports
pub use timestamps::Timestamps;
pub use timestamps::TimestampsBuilder;
pub use metadata::Metadata;
pub use metadata::MetadataBuilder;
