//! AutomationRun seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial AutomationRun data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// AUTOMATIONRUN SEEDER
// ============================================================================

/// Seeder for automation_run
pub struct SeedAutomationRunSeeder;

impl SeedAutomationRunSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedAutomationRunSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedAutomationRunSeeder {
    fn name(&self) -> &'static str {
        "SeedAutomationRunSeeder"
    }

    fn order(&self) -> i32 {
        2
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if foundation_ext.foundation_automation_runs table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM foundation_ext.foundation_automation_runs")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/automation_run_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM foundation_ext.foundation_automation_runs")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
