//! Repository trait for AutomationRun aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the AutomationRun aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{AutomationRun, FoundationRunStatus, FoundationTriggerKind};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AutomationRunPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl AutomationRunPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct AutomationRunPaginatedResult {
    pub data: Vec<AutomationRun>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AutomationRunFilter {
    pub automation_id: Option<Uuid>,
    pub trigger: Option<FoundationTriggerKind>,
    pub status: Option<FoundationRunStatus>,
    pub envelope_id: Option<String>,
    pub source_event_type: Option<String>,
    pub aggregate_id: Option<String>,
    pub parent_run_id: Option<Uuid>,
    pub detail: Option<String>,
}

impl AutomationRunFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.automation_id.is_some() || self.trigger.is_some() || self.status.is_some() || self.envelope_id.is_some() || self.source_event_type.is_some() || self.aggregate_id.is_some() || self.parent_run_id.is_some() || self.detail.is_some()
    }
}

/// Repository trait for AutomationRun aggregate
///
/// This trait defines the persistence contract for AutomationRun entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait AutomationRunRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new automation_run entity
    async fn save(&self, entity: &AutomationRun) -> Result<AutomationRun>;

    /// Find automation_run by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<AutomationRun>>;

    /// Find all automation_run entities
    async fn find_all(&self) -> Result<Vec<AutomationRun>>;

    /// Update automation_run by ID
    async fn update(&self, id: &str, entity: &AutomationRun) -> Result<Option<AutomationRun>>;

    /// Delete automation_run by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List automation_run with pagination
    async fn list(&self, params: AutomationRunPaginationParams) -> Result<AutomationRunPaginatedResult>;

    /// List automation_run with pagination and filters
    async fn list_with_filters(&self, params: AutomationRunPaginationParams, filters: AutomationRunFilter) -> Result<AutomationRunPaginatedResult>;

    /// Count all automation_run entities
    async fn count(&self) -> Result<u64>;

    /// Count automation_run entities matching filters
    async fn count_with_filters(&self, filters: AutomationRunFilter) -> Result<u64>;

    /// Check if automation_run exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete automation_run by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted automation_run by ID
    async fn restore(&self, id: &str) -> Result<Option<AutomationRun>>;

    /// List soft-deleted automation_run entities
    async fn list_deleted(&self, params: AutomationRunPaginationParams) -> Result<AutomationRunPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save automation_run entities
    async fn bulk_save(&self, entities: &[AutomationRun]) -> Result<Vec<AutomationRun>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
