//! Repository trait for AutomationRule aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the AutomationRule aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;

use crate::domain::entity::{AutomationRule, FoundationTriggerKind};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AutomationRulePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl AutomationRulePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct AutomationRulePaginatedResult {
    pub data: Vec<AutomationRule>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AutomationRuleFilter {
    pub name: Option<String>,
    pub description: Option<String>,
    pub model: Option<String>,
    pub trigger_kind: Option<FoundationTriggerKind>,
    pub trigger_pattern: Option<String>,
    pub time_field: Option<String>,
    pub active: Option<bool>,
    pub created_by_source: Option<String>,
}

impl AutomationRuleFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some() || self.description.is_some() || self.model.is_some() || self.trigger_kind.is_some() || self.trigger_pattern.is_some() || self.time_field.is_some() || self.active.is_some() || self.created_by_source.is_some()
    }
}

/// Repository trait for AutomationRule aggregate
///
/// This trait defines the persistence contract for AutomationRule entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait AutomationRuleRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new automation_rule entity
    async fn save(&self, entity: &AutomationRule) -> Result<AutomationRule>;

    /// Find automation_rule by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<AutomationRule>>;

    /// Find all automation_rule entities
    async fn find_all(&self) -> Result<Vec<AutomationRule>>;

    /// Update automation_rule by ID
    async fn update(&self, id: &str, entity: &AutomationRule) -> Result<Option<AutomationRule>>;

    /// Delete automation_rule by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List automation_rule with pagination
    async fn list(&self, params: AutomationRulePaginationParams) -> Result<AutomationRulePaginatedResult>;

    /// List automation_rule with pagination and filters
    async fn list_with_filters(&self, params: AutomationRulePaginationParams, filters: AutomationRuleFilter) -> Result<AutomationRulePaginatedResult>;

    /// Count all automation_rule entities
    async fn count(&self) -> Result<u64>;

    /// Count automation_rule entities matching filters
    async fn count_with_filters(&self, filters: AutomationRuleFilter) -> Result<u64>;

    /// Check if automation_rule exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete automation_rule by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted automation_rule by ID
    async fn restore(&self, id: &str) -> Result<Option<AutomationRule>>;

    /// List soft-deleted automation_rule entities
    async fn list_deleted(&self, params: AutomationRulePaginationParams) -> Result<AutomationRulePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save automation_rule entities
    async fn bulk_save(&self, entities: &[AutomationRule]) -> Result<Vec<AutomationRule>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
