//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod automation_rule_repository;
pub mod automation_run_repository;
pub mod scheduler_posture_repository;

// Re-exports
pub use automation_rule_repository::{
    AutomationRuleRepository,
    AutomationRulePaginationParams,
    AutomationRulePaginatedResult,
    AutomationRuleFilter,
};
pub use automation_run_repository::{
    AutomationRunRepository,
    AutomationRunPaginationParams,
    AutomationRunPaginatedResult,
    AutomationRunFilter,
};
pub use scheduler_posture_repository::{
    SchedulerPostureRepository,
    SchedulerPosturePaginationParams,
    SchedulerPosturePaginatedResult,
    SchedulerPostureFilter,
};
