//! Repository trait for SchedulerPosture aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the SchedulerPosture aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;

use crate::domain::entity::{SchedulerPosture, FoundationSchedulerPosture};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SchedulerPosturePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl SchedulerPosturePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct SchedulerPosturePaginatedResult {
    pub data: Vec<SchedulerPosture>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SchedulerPostureFilter {
    pub singleton: Option<bool>,
    pub posture: Option<FoundationSchedulerPosture>,
    pub last_deviation_note: Option<String>,
}

impl SchedulerPostureFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.singleton.is_some() || self.posture.is_some() || self.last_deviation_note.is_some()
    }
}

/// Repository trait for SchedulerPosture aggregate
///
/// This trait defines the persistence contract for SchedulerPosture entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait SchedulerPostureRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new scheduler_posture entity
    async fn save(&self, entity: &SchedulerPosture) -> Result<SchedulerPosture>;

    /// Find scheduler_posture by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<SchedulerPosture>>;

    /// Find all scheduler_posture entities
    async fn find_all(&self) -> Result<Vec<SchedulerPosture>>;

    /// Update scheduler_posture by ID
    async fn update(&self, id: &str, entity: &SchedulerPosture) -> Result<Option<SchedulerPosture>>;

    /// Delete scheduler_posture by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List scheduler_posture with pagination
    async fn list(&self, params: SchedulerPosturePaginationParams) -> Result<SchedulerPosturePaginatedResult>;

    /// List scheduler_posture with pagination and filters
    async fn list_with_filters(&self, params: SchedulerPosturePaginationParams, filters: SchedulerPostureFilter) -> Result<SchedulerPosturePaginatedResult>;

    /// Count all scheduler_posture entities
    async fn count(&self) -> Result<u64>;

    /// Count scheduler_posture entities matching filters
    async fn count_with_filters(&self, filters: SchedulerPostureFilter) -> Result<u64>;

    /// Check if scheduler_posture exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete scheduler_posture by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted scheduler_posture by ID
    async fn restore(&self, id: &str) -> Result<Option<SchedulerPosture>>;

    /// List soft-deleted scheduler_posture entities
    async fn list_deleted(&self, params: SchedulerPosturePaginationParams) -> Result<SchedulerPosturePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save scheduler_posture entities
    async fn bulk_save(&self, entities: &[SchedulerPosture]) -> Result<Vec<SchedulerPosture>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
