//! Repository for AutomationRule entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<AutomationRule, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::AutomationRule;

/// Table name for AutomationRule entities
pub const TABLE_NAME: &str = "foundation_ext.foundation_automation_rules";

/// Repository for AutomationRule entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct AutomationRuleRepository(
    backbone_orm::GenericCrudRepository<AutomationRule, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for AutomationRuleRepository {
    type Target = backbone_orm::GenericCrudRepository<AutomationRule, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl AutomationRuleRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(AutomationRuleRepository, AutomationRule, soft_delete);
