//! Repository for AutomationRun entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<AutomationRun, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::AutomationRun;

/// Table name for AutomationRun entities
pub const TABLE_NAME: &str = "foundation_ext.foundation_automation_runs";

/// Repository for AutomationRun entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct AutomationRunRepository(
    backbone_orm::GenericCrudRepository<AutomationRun, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for AutomationRunRepository {
    type Target = backbone_orm::GenericCrudRepository<AutomationRun, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl AutomationRunRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(AutomationRunRepository, AutomationRun, soft_delete);
