//! Repository for SchedulerPosture entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<SchedulerPosture, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::SchedulerPosture;

/// Table name for SchedulerPosture entities
pub const TABLE_NAME: &str = "foundation_ext.foundation_scheduler_posture";

/// Repository for SchedulerPosture entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SchedulerPostureRepository(
    backbone_orm::GenericCrudRepository<SchedulerPosture, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SchedulerPostureRepository {
    type Target = backbone_orm::GenericCrudRepository<SchedulerPosture, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SchedulerPostureRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(SchedulerPostureRepository, SchedulerPosture, soft_delete);
