//! Validator for AutomationRule entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<AutomationRule>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::AutomationRule;

/// Validator type alias for AutomationRule entities.
pub type AutomationRuleValidator = EntityValidator<AutomationRule>;

/// Build a validator for AutomationRule with all schema-defined field rules.
pub fn automation_rule_validator() -> AutomationRuleValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &AutomationRule| &e.name))
        .rule(OptionalNotBlank::new("description", |e: &AutomationRule| e.description.as_deref()))
        .rule(RequiredString::new("model", |e: &AutomationRule| &e.model))
        .rule(OptionalNotBlank::new("trigger_pattern", |e: &AutomationRule| e.trigger_pattern.as_deref()))
        .rule(OptionalNotBlank::new("time_field", |e: &AutomationRule| e.time_field.as_deref()))
        .rule(OptionalNotBlank::new("created_by_source", |e: &AutomationRule| e.created_by_source.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
