//! Validator for AutomationRun entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<AutomationRun>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::AutomationRun;

/// Validator type alias for AutomationRun entities.
pub type AutomationRunValidator = EntityValidator<AutomationRun>;

/// Build a validator for AutomationRun with all schema-defined field rules.
pub fn automation_run_validator() -> AutomationRunValidator {
    EntityValidator::new()
        .rule(RequiredString::new("envelope_id", |e: &AutomationRun| &e.envelope_id))
        .rule(OptionalNotBlank::new("source_event_type", |e: &AutomationRun| e.source_event_type.as_deref()))
        .rule(OptionalNotBlank::new("aggregate_id", |e: &AutomationRun| e.aggregate_id.as_deref()))
        .rule(OptionalNotBlank::new("detail", |e: &AutomationRun| e.detail.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
