//! Entity validators
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::{ValidationError, ValidationErrors, ValidationResult, EntityValidator};

pub mod automation_rule_validator;
pub mod automation_run_validator;
pub mod scheduler_posture_validator;

pub use automation_rule_validator::{AutomationRuleValidator, automation_rule_validator};
pub use automation_run_validator::{AutomationRunValidator, automation_run_validator};
pub use scheduler_posture_validator::{SchedulerPostureValidator, scheduler_posture_validator};

// <<< CUSTOM
// END CUSTOM
