//! Validator for SchedulerPosture entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<SchedulerPosture>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::SchedulerPosture;

/// Validator type alias for SchedulerPosture entities.
pub type SchedulerPostureValidator = EntityValidator<SchedulerPosture>;

/// Build a validator for SchedulerPosture with all schema-defined field rules.
pub fn scheduler_posture_validator() -> SchedulerPostureValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("last_deviation_note", |e: &SchedulerPosture| e.last_deviation_note.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
