//! FoundationExt Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::AutomationRuleService;
use crate::application::service::AutomationRunService;
use crate::application::service::SchedulerPostureService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// AutomationRule service
    pub automation_rule_service: Arc<AutomationRuleService>,
    /// AutomationRun service
    pub automation_run_service: Arc<AutomationRunService>,
    /// SchedulerPosture service
    pub scheduler_posture_service: Arc<SchedulerPostureService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        automation_rule_service: Arc<AutomationRuleService>,
        automation_run_service: Arc<AutomationRunService>,
        scheduler_posture_service: Arc<SchedulerPostureService>
    ) -> Self {
        Self {
            automation_rule_service,
            automation_run_service,
            scheduler_posture_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::FoundationExtModule) -> Self {
        Self {
            automation_rule_service: module.automation_rule_service.clone(),
            automation_run_service: module.automation_run_service.clone(),
            scheduler_posture_service: module.scheduler_posture_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    automation_rule_service: Option<Arc<AutomationRuleService>>,
    automation_run_service: Option<Arc<AutomationRunService>>,
    scheduler_posture_service: Option<Arc<SchedulerPostureService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the AutomationRule service.
    pub fn with_automation_rule_service(mut self, service: Arc<AutomationRuleService>) -> Self {
        self.automation_rule_service = Some(service);
        self
    }

    /// Set the AutomationRun service.
    pub fn with_automation_run_service(mut self, service: Arc<AutomationRunService>) -> Self {
        self.automation_run_service = Some(service);
        self
    }

    /// Set the SchedulerPosture service.
    pub fn with_scheduler_posture_service(mut self, service: Arc<SchedulerPostureService>) -> Self {
        self.scheduler_posture_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            automation_rule_service: self.automation_rule_service.expect("automation_rule_service is required"),
            automation_run_service: self.automation_run_service.expect("automation_run_service is required"),
            scheduler_posture_service: self.scheduler_posture_service.expect("scheduler_posture_service is required"),
        }
    }
}
