//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    automation_rule_handler::create_automation_rule_read_routes,
    automation_run_handler::create_automation_run_read_routes,
    scheduler_posture_handler::create_scheduler_posture_read_routes,
};

use crate::application::service::{
    AutomationRuleService,
    AutomationRunService,
    SchedulerPostureService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub automation_rule: Arc<AutomationRuleService>,
    pub automation_run: Arc<AutomationRunService>,
    pub scheduler_posture: Arc<SchedulerPostureService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // AutomationRule routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_automation_rule_read_routes(services.automation_rule))
        // AutomationRun routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_automation_run_read_routes(services.automation_run))
        // SchedulerPosture routes (READ-ONLY — append-only/event-sourced entity; writes arrive via the event handlers)
        .merge(create_scheduler_posture_read_routes(services.scheduler_posture))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn automation_rule_routes(service: Arc<AutomationRuleService>) -> Router {
        create_automation_rule_routes(service)
    }

    pub fn automation_run_routes(service: Arc<AutomationRunService>) -> Router {
        create_automation_run_routes(service)
    }

    pub fn scheduler_posture_routes(service: Arc<SchedulerPostureService>) -> Router {
        create_scheduler_posture_routes(service)
    }

}
