//! Public events for FoundationExt module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// AUTOMATIONRULE EVENTS
// ============================================================================

/// Event published when a AutomationRule is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AutomationRuleCreatedEvent {
    pub id: AutomationRuleId,
    pub data: AutomationRuleDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AutomationRule is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AutomationRuleUpdatedEvent {
    pub id: AutomationRuleId,
    pub data: AutomationRuleDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AutomationRule is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AutomationRuleDeletedEvent {
    pub id: AutomationRuleId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// AUTOMATIONRUN EVENTS
// ============================================================================

/// Event published when a AutomationRun is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AutomationRunCreatedEvent {
    pub id: AutomationRunId,
    pub data: AutomationRunDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AutomationRun is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AutomationRunUpdatedEvent {
    pub id: AutomationRunId,
    pub data: AutomationRunDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AutomationRun is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AutomationRunDeletedEvent {
    pub id: AutomationRunId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SCHEDULERPOSTURE EVENTS
// ============================================================================

/// Event published when a SchedulerPosture is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SchedulerPostureCreatedEvent {
    pub id: SchedulerPostureId,
    pub data: SchedulerPostureDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SchedulerPosture is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SchedulerPostureUpdatedEvent {
    pub id: SchedulerPostureId,
    pub data: SchedulerPostureDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SchedulerPosture is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SchedulerPostureDeletedEvent {
    pub id: SchedulerPostureId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by FoundationExt module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum FoundationExtEvent {
    AutomationRuleCreated(AutomationRuleCreatedEvent),
    AutomationRuleUpdated(AutomationRuleUpdatedEvent),
    AutomationRuleDeleted(AutomationRuleDeletedEvent),
    AutomationRunCreated(AutomationRunCreatedEvent),
    AutomationRunUpdated(AutomationRunUpdatedEvent),
    AutomationRunDeleted(AutomationRunDeletedEvent),
    SchedulerPostureCreated(SchedulerPostureCreatedEvent),
    SchedulerPostureUpdated(SchedulerPostureUpdatedEvent),
    SchedulerPostureDeleted(SchedulerPostureDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FoundationExtEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for FoundationExtEventMetadata {
    fn default() -> Self {
        Self {
            module: "foundation_ext",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
