//! FoundationExt Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that FoundationExt exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use foundation_ext::exports::{AutomationRuleDto};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `AutomationRuleDto` - Data transfer object for AutomationRule
/// - `AutomationRuleSummary` - Summary view of AutomationRule
/// - `AutomationRuleId` - Type-safe ID wrapper
/// - `AutomationRunDto` - Data transfer object for AutomationRun
/// - `AutomationRunSummary` - Summary view of AutomationRun
/// - `AutomationRunId` - Type-safe ID wrapper
/// - `SchedulerPostureDto` - Data transfer object for SchedulerPosture
/// - `SchedulerPostureSummary` - Summary view of SchedulerPosture
/// - `SchedulerPostureId` - Type-safe ID wrapper
///
/// ## Public Events
/// - `AutomationRuleCreatedEvent` - Published when AutomationRule is created
/// - `AutomationRuleUpdatedEvent` - Published when AutomationRule is updated
/// - `AutomationRuleDeletedEvent` - Published when AutomationRule is deleted
/// - `AutomationRunCreatedEvent` - Published when AutomationRun is created
/// - `AutomationRunUpdatedEvent` - Published when AutomationRun is updated
/// - `AutomationRunDeletedEvent` - Published when AutomationRun is deleted
/// - `SchedulerPostureCreatedEvent` - Published when SchedulerPosture is created
/// - `SchedulerPostureUpdatedEvent` - Published when SchedulerPosture is updated
/// - `SchedulerPostureDeletedEvent` - Published when SchedulerPosture is deleted
pub struct ExportSummary;
