//! Public types for FoundationExt module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use crate::domain::entity::*;

// ============================================================================
// AUTOMATIONRULE TYPES
// ============================================================================

/// Type-safe ID for AutomationRule
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct AutomationRuleId(pub Uuid);

impl AutomationRuleId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for AutomationRuleId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<AutomationRuleId> for Uuid {
    fn from(id: AutomationRuleId) -> Self {
        id.0
    }
}

/// Data transfer object for AutomationRule
///
/// This is the public representation of AutomationRule for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AutomationRuleDto {
    pub id: AutomationRuleId,
    pub name: String,
    pub description: Option<String>,
    pub model: String,
    pub trigger_kind: FoundationTriggerKind,
    pub trigger_pattern: Option<String>,
    pub time_field: Option<String>,
    pub delay_minutes: Option<i32>,
    pub actions: serde_json::Value,
    pub active: bool,
    pub created_by_source: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of AutomationRule for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AutomationRuleSummary {
    pub id: AutomationRuleId,
    pub name: String,
}

/// Reference to AutomationRule for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AutomationRuleRef {
    pub id: AutomationRuleId,
}

// ============================================================================
// AUTOMATIONRUN TYPES
// ============================================================================

/// Type-safe ID for AutomationRun
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct AutomationRunId(pub Uuid);

impl AutomationRunId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for AutomationRunId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<AutomationRunId> for Uuid {
    fn from(id: AutomationRunId) -> Self {
        id.0
    }
}

/// Data transfer object for AutomationRun
///
/// This is the public representation of AutomationRun for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AutomationRunDto {
    pub id: AutomationRunId,
    pub automation_id: Uuid,
    pub trigger: FoundationTriggerKind,
    pub status: FoundationRunStatus,
    pub envelope_id: String,
    pub source_event_type: Option<String>,
    pub aggregate_id: Option<String>,
    pub parent_run_id: Option<Uuid>,
    pub depth: i32,
    pub actions_applied: serde_json::Value,
    pub effect_event_ids: serde_json::Value,
    pub detail: Option<String>,
    pub occurred_at: DateTime<Utc>,
    pub metadata: serde_json::Value,
}

/// Summary view of AutomationRun for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AutomationRunSummary {
    pub id: AutomationRunId,
    pub status: FoundationRunStatus,
}

/// Reference to AutomationRun for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AutomationRunRef {
    pub id: AutomationRunId,
}

// ============================================================================
// SCHEDULERPOSTURE TYPES
// ============================================================================

/// Type-safe ID for SchedulerPosture
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SchedulerPostureId(pub Uuid);

impl SchedulerPostureId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for SchedulerPostureId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<SchedulerPostureId> for Uuid {
    fn from(id: SchedulerPostureId) -> Self {
        id.0
    }
}

/// Data transfer object for SchedulerPosture
///
/// This is the public representation of SchedulerPosture for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SchedulerPostureDto {
    pub id: SchedulerPostureId,
    pub singleton: bool,
    pub posture: FoundationSchedulerPosture,
    pub time_rule_count: i32,
    pub min_delay_minutes: Option<i32>,
    pub interval_minutes: Option<i32>,
    pub last_evaluated_at: Option<DateTime<Utc>>,
    pub last_fired_count: i32,
    pub last_deviation_note: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of SchedulerPosture for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SchedulerPostureSummary {
    pub id: SchedulerPostureId,
}

/// Reference to SchedulerPosture for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SchedulerPostureRef {
    pub id: SchedulerPostureId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
