//! FoundationExt Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::AutomationRuleService;
pub use application::service::AutomationRunService;
pub use application::service::SchedulerPostureService;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// FoundationExt module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let foundation_ext = FoundationExtModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = foundation_ext.all_crud_routes();
/// ```
pub struct FoundationExtModule {
    pub(crate) automation_rule_service: Arc<AutomationRuleService>,
    pub(crate) automation_run_service: Arc<AutomationRunService>,
    pub(crate) scheduler_posture_service: Arc<SchedulerPostureService>,
    // <<< CUSTOM FIELDS
    /// The fail-closed gateway slot the host fills at compose time (the
    /// module's ONLY reach into watched modules' records).
    pub(crate) gateway_slot: Arc<application::service::gateway_port::AutomationGatewaySlot>,
    /// The guarded rule administration service (the only rule writer).
    pub(crate) rule_service: Arc<application::service::rule_service::RuleService>,
    /// The reaction engine — register on the HOST's integration bus; this
    /// module never self-registers.
    pub(crate) reaction_handler:
        Arc<application::service::reaction_engine::AutomationReactionHandler>,
    /// The declared-posture scheduler — the host's timer loop calls
    /// `evaluate_tick`; the module owns no threads.
    pub(crate) scheduler:
        Arc<application::service::scheduler_service::AutomationScheduler>,
    // END CUSTOM
}

impl FoundationExtModule {
    /// Create a new module builder
    pub fn builder() -> FoundationExtModuleBuilder {
        FoundationExtModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_automation_rule_read_routes,
            create_automation_run_read_routes,
            create_scheduler_posture_read_routes,
        };

        Router::new()
            .merge(create_automation_rule_read_routes(self.automation_rule_service.clone()))
            .merge(create_automation_run_read_routes(self.automation_run_service.clone()))
            .merge(create_scheduler_posture_read_routes(self.scheduler_posture_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD; prefer readonly_routes() + validated writes, or all_crud_routes() for the full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }

    /// Read-only routes for every entity (GET endpoints only) — the safe base.
    ///
    /// Generic mutation can't reach here, so this surface cannot bypass a
    /// validated write service's invariants. Use this as the production base and
    /// merge validated write routes (or a write service's HTTP layer) onto it.
    pub fn readonly_routes(&self) -> Router {
        use presentation::http::{
            create_automation_rule_read_routes,
            create_automation_run_read_routes,
            create_scheduler_posture_read_routes,
        };

        Router::new()
            .merge(create_automation_rule_read_routes(self.automation_rule_service.clone()))
            .merge(create_automation_run_read_routes(self.automation_run_service.clone()))
            .merge(create_scheduler_posture_read_routes(self.scheduler_posture_service.clone()))
    }

    // <<< CUSTOM METHODS
    /// The shared fail-closed gateway slot.
    pub fn gateway_slot(
        &self,
    ) -> &Arc<application::service::gateway_port::AutomationGatewaySlot> {
        &self.gateway_slot
    }

    /// Install the HOST's gateway adapter (compose time). Until this is
    /// called, every fire refuses loudly as NotComposed — fail-closed by
    /// design (the survey certification-port precedent).
    pub fn install_gateway(
        &self,
        gateway: Arc<dyn application::service::gateway_port::AutomationGateway>,
    ) {
        self.gateway_slot.install(gateway);
    }

    /// Whether a gateway adapter is installed (compose-time diagnostics:
    /// warn loudly when a module that has rules is unwired).
    pub fn gateway_is_wired(&self) -> bool {
        self.gateway_slot.is_wired()
    }

    /// The guarded rule administration service (create/replace/activate/
    /// retire/list — the only writer of automation rules; all generated
    /// route surfaces are read-only).
    pub fn rule_service(&self) -> &application::service::rule_service::RuleService {
        &self.rule_service
    }

    /// The reaction engine. The HOST registers this handler on its
    /// integration bus (`bus.subscribe(module.reaction_handler())`) and
    /// relays its own outbox onto that bus; the handler subscribes with
    /// pattern `"*"` and does its own rule-pattern matching.
    pub fn reaction_handler(
        &self,
    ) -> &Arc<application::service::reaction_engine::AutomationReactionHandler> {
        &self.reaction_handler
    }

    /// The declared-posture scheduler. The host's timer loop calls
    /// `scheduler().evaluate_tick(now)` at the interval the posture row
    /// records; with no live time rules the posture is `inactive` and a
    /// tick is a no-op.
    pub fn scheduler(
        &self,
    ) -> &Arc<application::service::scheduler_service::AutomationScheduler> {
        &self.scheduler
    }
    // END CUSTOM
}

/// Builder for FoundationExtModule
pub struct FoundationExtModuleBuilder {
    db_pool: Option<PgPool>,
}

impl FoundationExtModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<FoundationExtModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // AutomationRule service
        let automation_rule_repository = Arc::new(AutomationRuleRepository::new(db_pool.clone()));
        let automation_rule_service = Arc::new(AutomationRuleService::with_repository(automation_rule_repository.clone()));

        // AutomationRun service
        let automation_run_repository = Arc::new(AutomationRunRepository::new(db_pool.clone()));
        let automation_run_service = Arc::new(AutomationRunService::with_repository(automation_run_repository.clone()));

        // SchedulerPosture service
        let scheduler_posture_repository = Arc::new(SchedulerPostureRepository::new(db_pool.clone()));
        let scheduler_posture_service = Arc::new(SchedulerPostureService::with_repository(scheduler_posture_repository.clone()));

        // <<< CUSTOM
        // Hand services share one fail-closed gateway slot: the reaction
        // engine and the scheduler both reach watched modules only through
        // it, and the host installs its adapter once at compose time.
        let gateway_slot = Arc::new(
            application::service::gateway_port::AutomationGatewaySlot::new(),
        );
        let rule_service = Arc::new(application::service::rule_service::RuleService::new(
            db_pool.clone(),
        ));
        let reaction_handler =
            Arc::new(application::service::reaction_engine::AutomationReactionHandler::new(
                db_pool.clone(),
                gateway_slot.clone(),
                application::service::reaction_engine::DEFAULT_CAUSAL_DEPTH_CAP,
            ));
        let scheduler = Arc::new(
            application::service::scheduler_service::AutomationScheduler::new(
                db_pool.clone(),
                gateway_slot.clone(),
                application::service::scheduler_service::LadderConfig::default(),
            ),
        );
        // END CUSTOM

        Ok(FoundationExtModule {
            automation_rule_service,
            automation_run_service,
            scheduler_posture_service,
            // <<< CUSTOM
            gateway_slot,
            rule_service,
            reaction_handler,
            scheduler,
            // END CUSTOM
        })
    }
}

impl Default for FoundationExtModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
