//! FoundationExt Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;

// The module's extension (hand-written; ADR-0031).
#[path = "lib.ext.rs"]
mod lib_ext;
pub use lib_ext::*;
/// This crate's module and builder under fixed names, for the extension's `impl` blocks.
#[allow(dead_code)]
pub(crate) type ThisModule = FoundationExtModule;
#[allow(dead_code)]
pub(crate) type ThisModuleBuilder = FoundationExtModuleBuilder;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::AutomationRuleService;
pub use application::service::AutomationRunService;
pub use application::service::SchedulerPostureService;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// FoundationExt module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let foundation_ext = FoundationExtModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = foundation_ext.all_crud_routes();
/// ```
pub struct FoundationExtModule {
    pub(crate) automation_rule_service: Arc<AutomationRuleService>,
    pub(crate) automation_run_service: Arc<AutomationRunService>,
    pub(crate) scheduler_posture_service: Arc<SchedulerPostureService>,
    /// The module's extension state (`lib.ext.rs`); its fields read through `Deref`.
    pub(crate) ext: ModuleExt,
}

impl std::ops::Deref for FoundationExtModule {
    type Target = ModuleExt;
    fn deref(&self) -> &Self::Target {
        &self.ext
    }
}

impl std::ops::DerefMut for FoundationExtModule {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.ext
    }
}

/// What the extension's `build` hook receives from the generated build (ADR-0031).
#[allow(dead_code)]
pub(crate) struct ModuleParts<'a> {
    pub(crate) db_pool: &'a PgPool,
    pub(crate) automation_rule_service: &'a Arc<AutomationRuleService>,
    pub(crate) automation_rule_repository: &'a Arc<AutomationRuleRepository>,
    pub(crate) automation_run_service: &'a Arc<AutomationRunService>,
    pub(crate) automation_run_repository: &'a Arc<AutomationRunRepository>,
    pub(crate) scheduler_posture_service: &'a Arc<SchedulerPostureService>,
    pub(crate) scheduler_posture_repository: &'a Arc<SchedulerPostureRepository>,
}

impl FoundationExtModule {
    /// Create a new module builder
    pub fn builder() -> FoundationExtModuleBuilder {
        FoundationExtModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_automation_rule_read_routes,
            create_automation_run_read_routes,
            create_scheduler_posture_read_routes,
        };

        Router::new()
            .merge(create_automation_rule_read_routes(self.automation_rule_service.clone()))
            .merge(create_automation_run_read_routes(self.automation_run_service.clone()))
            .merge(create_scheduler_posture_read_routes(self.scheduler_posture_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD; prefer readonly_routes() + validated writes, or all_crud_routes() for the full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }

    /// Read-only routes for every entity (GET endpoints only) — the safe base.
    ///
    /// Generic mutation can't reach here, so this surface cannot bypass a
    /// validated write service's invariants. Use this as the production base and
    /// merge validated write routes (or a write service's HTTP layer) onto it.
    pub fn readonly_routes(&self) -> Router {
        use presentation::http::{
            create_automation_rule_read_routes,
            create_automation_run_read_routes,
            create_scheduler_posture_read_routes,
        };

        Router::new()
            .merge(create_automation_rule_read_routes(self.automation_rule_service.clone()))
            .merge(create_automation_run_read_routes(self.automation_run_service.clone()))
            .merge(create_scheduler_posture_read_routes(self.scheduler_posture_service.clone()))
    }

}

/// Builder for FoundationExtModule
pub struct FoundationExtModuleBuilder {
    db_pool: Option<PgPool>,
    /// The builder's extension state (`lib.ext.rs`); its fields read through `Deref`.
    ext: ModuleBuilderExt,
}

impl std::ops::Deref for FoundationExtModuleBuilder {
    type Target = ModuleBuilderExt;
    fn deref(&self) -> &Self::Target {
        &self.ext
    }
}

impl std::ops::DerefMut for FoundationExtModuleBuilder {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.ext
    }
}

impl FoundationExtModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
            ext: Default::default(),
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }


    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<FoundationExtModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // AutomationRule service
        let automation_rule_repository = Arc::new(AutomationRuleRepository::new(db_pool.clone()));
        let automation_rule_service = Arc::new(AutomationRuleService::with_repository(automation_rule_repository.clone()));

        // AutomationRun service
        let automation_run_repository = Arc::new(AutomationRunRepository::new(db_pool.clone()));
        let automation_run_service = Arc::new(AutomationRunService::with_repository(automation_run_repository.clone()));

        // SchedulerPosture service
        let scheduler_posture_repository = Arc::new(SchedulerPostureRepository::new(db_pool.clone()));
        let scheduler_posture_service = Arc::new(SchedulerPostureService::with_repository(scheduler_posture_repository.clone()));


        // The extension builds its own state from what the generated build made.
        let ext = self.ext.build(&ModuleParts {
            db_pool: &db_pool,
            automation_rule_service: &automation_rule_service,
            automation_rule_repository: &automation_rule_repository,
            automation_run_service: &automation_run_service,
            automation_run_repository: &automation_run_repository,
            scheduler_posture_service: &scheduler_posture_service,
            scheduler_posture_repository: &scheduler_posture_repository,
        })?;

        Ok(FoundationExtModule {
            automation_rule_service,
            automation_run_service,
            scheduler_posture_service,
            ext,
        })
    }
}

impl Default for FoundationExtModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
